### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by AyazSardar** [nweber/SystemVolumeNativeExtension#1]
Hi,

I tried using this ANE under Flash CS 5.5. When i did a build in cmd i received the following error:

ld: unknown option: -ios_version_min
Compilation failed while executing : ld64

I am using Windows 7 command prompt to build my IPA file.

What am i doing wrong here?

**Comment by nweber** [comment]
You must compile on a machine running OSX and you must specify the location of the iOS SDK when compiling the Flash application.  The README includes instructions for Flash Builder and other valuable information.  When building using the command line you must use the -platformsdk option for the iPhone-ARM platform.  See here http://help.adobe.com/en_US/air/build/WS901d38e593cd1bac1e63e3d128cdca935b-8000.html for more details.

There's more information about using iOS native extensions here http://www.digitalprimates.net/author/nweber/2012/04/10/building-a-native-extension-part-3/.  There's some information about why you must compile the IPA on a machine running OSX.

Nathan

-----Original Message-----
From: ASardar [mailto:reply@reply.github.com]
Sent: Monday, April 23, 2012 4:40 AM
To: Nathan Weber
Subject: [SystemVolumeNativeExtension] Build error (#1)

Hi,

I tried using this ANE under Flash CS 5.5. When i did a build in cmd i received the following error:

ld: unknown option: -ios_version_min
Compilation failed while executing : ld64

I am using Windows 7 command prompt to build my IPA file.

What am i doing wrong here?

---

Reply to this email directly or view it on GitHub:
https://github.com/nweber/SystemVolumeNativeExtension/issues/1
Notice: This transmission is intended only for the use of the individual or entity to which it is addressed and may contain information that is privileged or confidential. Any dissemination, distribution or copying of this transmission by anyone other than the intended recipient is strictly prohibited. If you have received this transmission in error, please notify the sender immediately by e-mail or telephone and delete the original transmission. Thank you.

**Comment by AyazSardar** [comment]
Hi Nathan,

Thanks for the answer, sadly i don't have Flash CS5.5 for the Mac. Will have to find another solution.

Ayaz

**Comment by nweber** [comment]
No problem.  It's a pain that AIR applications for iOS using native natives have to be compiled on OSX.  Hopefully Adobe can figure out a better solution soon.

I'd like to point out that you may not need CS5.5 for the Mac.  You should only need to package the IPA via command line on OSX.  I'm thinking you could compile the AIR application on windows, and copy the required files (swf, app descriptor, etc) onto the Mac, and then package the IPA there in the Terminal.
